### ISSUE TITLE
EU B2B rule

### ISSUE THREAD

**Issue by Tychodewaard** [HotcakesCommerce/hotcakes-commerce-core#155]
### Describe the solution you'd like
EU requires VAT not to be calculated within the EU when:
- The transaction is B2B
- The invoice address and the shipping address are not in the same country as the shop country.

In an ideal world this setup is flexible as the actual law is a more complex. https://www.baldwin.agency/blog/management/vat-rules-for-webshops/

But the first stated rule covers most situations, I think. 
That is: I have no private persons as customers and no companies that exceed thresholds in other countries.

**Comment by Navilois** [comment]
#216

**Comment by Navilois** [comment]
#216

**Comment by Navilois** [comment]
I'm running into similar problems in my B2B only shop. What it comes down to is the tax exemption number. I've implemented the input at checkout, but I need to remove tax once a valid tax exemption number has been added.
This needs to be overruled by tax rules for specific EU countries though.

I'll have a solution soon (tm)

**Comment by Navilois** [comment]
It appears Soon (tm) = 8 months in this case.
I have a working solution in a custom controller. However I believe it would benefit Hotcakes greatly to implement this enhancement for EU users - it's a must have for European webshops.

This is the basic commit for Hotcakes: https://github.com/Navilois/hotcakes-commerce-core/commit/d7672316d3d5ca6cd86d2edc87c71c2bf2f8564d


Basic concept:

- There's a VatNumber input [id="@(Model.Prefix + "vatnumber")"] at _CheckoutAddress.cshtml
- OnChange() calls Checkout.js / ApplyEUVatRules() -> AJAX Request to Checkout/ApplyEUVatRules
- If it's a valid VAT number and the store's country != the VAT number country -> set all order.Items to TaxExempt = true
- Refresh the totals table


Remarks:

- Can't use user.TaxExempt, because there's no user yet when using GuestCheckout.

- I'm using a custom workflow to store the VAT number in the TaxExemptionNumber field of the user later when processing the order

- Possible breaking change when resetting the TaxExempt flag to false on invalid VAT numbers - items that have been legit TaxExempt aren't any longer. Requires a little more work, e.g. don't set to false but to the LineItem value.


Todo:
 
- Admin setting to activate EU VAT rules

- RegEx is hardcoded in this commit. It won't change often (Brexit is next) but it's definitely not best practice ;)

There's probably some more things to think about, which exceed my knowledge of Hotcakes. If you're willing to put some work into this, I'll be happy to help implementing a proper solution @hismightiness

**Comment by Navilois** [comment]
This PR is live at https://www.sierzega.com/en-us/products/checkout

- Moved it from a custom controller to my Hotcakes fork
- Fixed the item.TaxExempt reset to reflect the products default
- Still missing feedback to the user on invald VAT. Coming soon (tm)

**Comment by Navilois** [comment]
Added localized validation msg via controller.resx
